# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-21 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CureData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('image', models.ImageField(blank=True, upload_to='photos', verbose_name='\u56fe\u7247')),
            ],
        ),
    ]
