# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-21 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curedata',
            old_name='image',
            new_name='file',
        ),
    ]
